site_name: Futures testnet API Docs
nav:
    - GENERAL INFO: general_info.md
    - MARKET DATA: market_data.md 
    - ACCOUNT/TRADE: trade_and_account.md 
    - ERROR INFO: errors.md
     
theme: readthedocs
